Add environmental variable while build close #29
RTUITLab/Landing-Front pull request #31
Opened 2021-04-01 16:23 UTC by Suput

Scrpt prevents user's mistakes:
1 - User has aleary added year -- build will replace it
2 - User added more then one year  -- build will erase all and insert new
3 - If no env file -- create it and insert only year

2021-04-01 20:00 UTC, CAPCHIK requested changes

2021-04-01 20:00 UTC, CAPCHIK commented on Jakefile
> +        exec("npm i && npm run buildToDeploy", (err, stdout, stderr) => {
`npm i` обновит пакеты, что не годится для prod сборки, в azure devops специально было `npm ci`

2021-04-01 20:59 UTC, Suput commented on Jakefile
> +        exec("npm i && npm run buildToDeploy", (err, stdout, stderr) => {
Понял, тогда в ITLab надо тоже сделать `ci`..

2021-04-03 13:32 UTC, CAPCHIK commented on Jakefile
> +                data = `${ENV_REACT_APP_BUILD_YEAR_ROW}\n${data}`;
Для чего разбивать на строки, если регулярка сама за один проход и так все проверит?

2021-04-03 13:33 UTC, CAPCHIK commented on Jakefile
> +                data = `${ENV_REACT_APP_BUILD_YEAR_ROW}\n${data}`;
А, если кто-то додумался несколько раз год написать...
Ну, хз на самом деле, насколько это надо

2021-04-03 13:49 UTC, Suput commented
Потому что была задача "год во время сборки" и я решил обезопасить год насколько можно, чтобы если кто-то случайно добавит, да и ещё несколько раз: то как поведёт себя фронт? А если будут дублироваться другие переменные: ошибка программиста

2021-04-03 14:08 UTC, CAPCHIK approved these changes

2021-04-03 14:08 UTC, merged