Add .env file creating before build
RTUITLab/Landing-Front pull request #34
Opened 2021-09-10 13:25 UTC by Suput

2021-09-10 14:23 UTC, CAPCHIK reviewed
А feedback api уже поднято?

2021-09-11 10:41 UTC, CAPCHIK approved these changes

2021-09-11 10:44 UTC, CAPCHIK commented
Пока не сливаем, слил в develop, давай проверим, что там все равботает

2021-09-11 10:45 UTC, CAPCHIK commented
Вот, о том и речь

https://dev.azure.com/rtuitlab/RTU%20IT%20Lab/_build/results?buildId=4946&view=results
@Suput

2021-09-11 10:46 UTC, CAPCHIK requested changes
Необходимо сначала протестировать на ветке `develop`

2021-09-12 05:26 UTC, CAPCHIK commented
Сделал на dev версии, шлет корректно, и даже отображается.

Не могу подтвердить данный PR, пока нет фронта в системе управления.

Должен отметить, что на dev версии если после обратной связи переключиться на отчеты, которые, кстати, не откроются, и потом вернуться - снова ничего не заработает. Пока способ отображения обращений реализован так - сливать это нельзя в мастер

2021-09-14 09:04 UTC, Suput commented
@CAPCHIK точно на деве работает? Я не могу открыть сайт
![image](https://user-images.githubusercontent.com/40500378/133228972-61398f0c-5ad0-4e5d-b8e1-4d6d71f32fd7.png)

2021-09-14 09:24 UTC, CAPCHIK commented
Разумеется не можешь войти, адрес то https://dev.manage.rtuitlab.dev/

2021-09-20 08:33 UTC, Suput commented
@CAPCHIK только что проверил работу дев лэндинга и дев сайта. Отправив отзыв, я увидел его на сайте. Думаю, это победа

2021-09-20 08:35 UTC, CAPCHIK commented
Я вроде тоже это делал, и тоже видел))
Но да, это в любом случае победа)

2021-09-20 10:05 UTC, merged