V2
RTUITLab/Landing-Front pull request #47
Opened 2022-02-18 18:36 UTC by baikinkirill

2022-02-21 13:05 UTC, IvLaptev requested changes
Написал огромный текст, а страница решила обновиться и всё стёрлось(
Пишу по памяти.

- [ ] Галерею практически полностью пропустил, но гора попыток влияния на css из js мне сильно не нравится. Буду это смотреть, когда появятся данные.
- [x] На ширине 960px оборудование налезает друг на друга
![image](https://user-images.githubusercontent.com/23360152/154960166-5e6ce479-95c8-4584-b5d2-66bf226cd0b9.png)

- [ ] Карусель работает неправильно где-то, ибо подкладывает битые картинки под каждую нормальную.
![image](https://user-images.githubusercontent.com/23360152/154960407-4f5b4cfa-b4f0-4cc2-b770-2e4d8dfc9ae3.png)

- [x] Почему на странице нет скролла?
- [ ] Раз мы думаем про SEO, давайте вёрстку семантическую использовать.
- [ ] В репозитории есть файлы с шаблонами проектов и достижений, которые нигде не используются.
- [ ] Не понимаю директории `parser`, `other`, которые лежат в корне.
- [ ] Везде, где должны быть данные, надо их добавить. Если не через fetch, то хотя бы через json.

2022-02-21 13:06 UTC, IvLaptev commented
Также в PR я не нашёл описание того, что было добавлено, поэтому смотрел вообще всё подряд.

2022-02-21 13:07 UTC, IvLaptev commented
Все изменения в `Jakefile` и `azure-pipelines.yml` будут смотреться позже и скорее всего не мной.

2022-02-22 18:58 UTC, baikinkirill commented on src/components/Header/Header.tsx
> +      })
Если использовать чисто якоря, то не будет анимации прокрутки при нажатии

2022-02-22 19:20 UTC, baikinkirill commented on src/pages/Index/Index.tsx
> +  const appContainer: any = useRef<HTMLDivElement>()
Чтобы при скролле страницы определялась активная вкладка. К примеру, изначально находились в самом верху, затем сами проскроллили до оборудования. Соответственно нужно отобразить это в меню.

Конкретно через этот реф определяется положение дочерних элементов, чтобы узнать, где пользователь сейчас

2022-02-23 10:54 UTC, baikinkirill commented on src/modules/IndexSections/Equipment/Equipment.tsx
> +    }, 0)
Изначально предполагалось, что элементы будут появляться с задержкой. Но в целом это можно реализовать проще, поетому да

2022-02-24 12:44 UTC, IvLaptev commented on src/components/Header/Header.tsx
> +      })
Будет. В CSS есть `scroll-behavior`. [Документация](https://developer.mozilla.org/ru/docs/Web/CSS/scroll-behavior)

2022-02-28 21:21 UTC, baikinkirill commented on src/components/StatusBar/StatusBar.tsx
> +            </div>
Активный таб может изменять сама галерея при прокрутке, radio button придется изменять вручную, а тут через state

2022-03-05 20:21 UTC, closed without merging